# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "J's Study Blog"
email: leejihee950430@gmail.com
description: "I record what I study everyday"
baseurl: "/jekyll-help-center-theme"
url: "http://quinalha.me"
twitter_username: "gustavoquinalha"
github_username:  "gustavoquinalha"
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
baseurl:
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
